parameters:

    ezperformancelogger.kernel_event_listener.class: GGGeek\eZPerformanceLoggerBundle\EventListener\PerfLogger

services:

    ezperformancelogger.kernel_event_listener:
        class: %ezperformancelogger.kernel_event_listener.class%
        # change the 2nd parameter to a value of 1 if the loggers set up in ezperformancelogger.ini need to rewrite page output (ex: piwik, ga loggers)
        arguments: [ @ezpublish_legacy.kernel, 0 ]
        tags:
            - { name: kernel.event_subscriber }
